<?php

use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\VarDumper\VarDumper;

function gcaba_portal_autenticidad_theme($existing, $type,$theme,$path)
{
    return [
        'autenticidadtema' => [
            'variables' =>  ['documento' => null]]
        ];
}


function gcaba_portal_autenticidad_form_alter(&$form, FormStateInterface $form_state, $form_id) {

    //$form['#attached']['library'][] = 'gcaba_portal_autenticidad/gcaba_portal_autenticidad';
    $values = $form_state->getValue('documento');
     if (!empty($values)) {
        $form['hola'] = [
            '#tipe' => 'markup',
            '#markup' => '<h1>Submission sent</h1>',
        ];

        return $form;
    } 
  }
